# --- Configuração do Site Principal (bizumatica.github.io) ---
baseURL = "https://bizumatica.github.io/"
languageCode = "pt-br"
title = "Bizumatica"
theme = "terminal"
publishDir = "docs"

enableEmoji = true

[pagination]
  pagerSize = 5

[params]
  themeColor = "green" 
  fullWidthTheme = false
  centerTheme = true
  animatedTheme = true
  customCSS = ["css/extended.css"]

[params.Logo]
  logoText = "Bizumática"

[params.csp]
  enable = true
  # 'self' significa imagens do próprio site
  img-src = " 'self' https://hits.seeyoufarm.com https://img.shields.io https://visitor-badge.laobi.icu "

[menu]
  [[menu.main]]
    identifier = "blog"
    name = ":: Acessar Blog ::"
    url = "/bizumatica-blog/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  category = "categories"