baseURL = "https://bizumatica.github.io/"
languageCode = "pt-br"
title = "Bizumática"
theme = "terminal"
publishDir = "docs"
enableEmoji = true

# Segurança e URLs limpas
canonifyURLs = true
relativeURLs = false

[slug]
  removePathAccents = true # Transforma "Matemática" em "matematica" automaticamente

[params]
  # Configurações de Design
  themeColor = "orange"
  fullWidthTheme = false
  centerTheme = true
  animatedTheme = true
  
  # O CSS que contém o Turquesa, Rosa e os Boxes de Bizu
  customCSS = ["css/extended.css"]

  [params.Logo]
    logoText = "Bizumática"
    logoHomeLink = "/"

# Navegação Principal
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Linux"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "matematica"
    name = "Matemática"
    url = "/matematica/"
    weight = 15
  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about/"
    weight = 20

# Configurações de Renderização (Essencial para KaTeX e Boxes)
[markup]
  [markup.goldmark.renderer]
    unsafe = true # Permite HTML dentro do Markdown (necessário para os shortcodes)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"

# Garante que o Hugo gere o site em HTML corretamente
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]