# --- Configuração do Site Principal (bizumatica.github.io) ---
baseURL = "https://bizumatica.github.io/"
languageCode = "pt-br"
title = "Bizumatica"
theme = "terminal"
publishDir = "docs"

[pagination]
  pagerSize = 5

[params]
  themeColor = "green" 
  fullWidthTheme = false
  centerTheme = true
  animatedTheme = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = ":: Acessar Blog ::"
    url = "/bizumatica-blog/"